server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

        - id: zone-service
          uri: lb://zone-service
          predicates:
            - Path=/api/v1/zones/**
          filters:
            - AuthenticationFilter

        - id: sensor-service
          uri: lb://sensor-service
          predicates:
            - Path=/api/v1/sensors/**
          filters:
            - AuthenticationFilter

        - id: sensor-service
          uri: lb://sensor-service
          predicates:
            - Path=/api/v1/sensors/**
          filters:
            - AuthenticationFilter

        - id: automation-and-controller-service
          uri: lb://automation-and-controller-service
          predicates:
            - Path=/api/v1/automation/**
          filters:
            - AuthenticationFilter

        - id: crop-service
          uri: lb://crop-service
          predicates:
            - Path=/api/v1/crops/**
          filters:
            - AuthenticationFilter